#theme: minima
#markdown: kramdown
markdown: CommonMarkGhPages

# Setup
title:            BlackDoc
tagline:          Black Theme for Jekyll
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              /
baseurl:          /BlackDoc/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Karlo Espiritu
  url:            https://twitter.com/karloespiritu

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/twocolumn/BlackDoc

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme          # brilliant
  - jekyll-sass-converter        # https://jekyllrb.com/docs/assets/
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


# jekyll-commonmark-ghpages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com

# jekyll-optional-front-matter
include:
  - docs/CONTRIBUTING.md

# jekyll-paginate
paginate:         1
paginate_path:    '/:num'

# jekyll-remote-theme
#remote_theme: esovm/minima
